version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../app:/app
      - ../app/node_modules:/app/node_modules
    ports:
      - "8000:8000"
    user: node
    stdin_open: true
    tty: true

volumes:
  node_modules:
